<a href="https://colab.research.google.com/github/Rajaanthonysamy/tensor-flow/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d=tf.constant([1,2,3])
print(tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
tensor_two_d=tf.constant([[1,2,3],
                          [4,5,6]])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
tensor_three_d=tf.constant([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[4,5,8]]
])
tensor_three_d

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [4, 5, 8]]], dtype=int32)>

In [11]:
tensor_one_d=tf.constant([1,2,3],dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float16)


In [12]:
tensor_one_d=tf.constant([1,2,3],dtype=tf.int16)
print(tensor_one_d)

casted_tensor_one_d=tf.cast(tensor_one_d,dtype=tf.float16)
print(casted_tensor_one_d)

tf.Tensor([1 2 3], shape=(3,), dtype=int16)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float16)


In [14]:
import numpy as np
np_array=np.array([1,2,3])

In [15]:
np_array_to_tf=tf.convert_to_tensor(np_array)
print(np_array_to_tf)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [26]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

In [27]:
eye_tensor

<tf.Tensor: shape=(2, 5, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [28]:
tf_fill=tf.fill([2,3],9)

In [29]:
tf_fill

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]], dtype=int32)>